substitutions:
  devicename: ambientales
  humanname: Ambientales

esphome:
  name: $devicename

esp8266:
  board: esp01_1m

# Activa el registro, para poder debuggear facilmente
logger:

# Activa el API de Home Assistant
api:
  encryption:
    key: "theAPIkey"

# Activa la funcion OTA (poder actualizar via wifi)
ota:
  password: "theOTApassword"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: high # Reduce el consumo del ESP8266 (no hace falta en ESP32)

# Activar puerto I2C
i2c:

# Define los sensores
sensor:
  - platform: bme680
    update_interval: 5min
    address: 0x77
    heater:
      duration: 2s
      temperature: 400
    temperature:
      name: "Temperatura BME680"
    humidity:
      name: "Humedad BME680"
    pressure:
      name: "Presión atmosférica BME680"
    gas_resistance:
      name: "Resistencia del sensor BME680"
